create database Hospital;

create table Convenio(
	COD_CONVENIO INT PRIMARY KEY,
	CPF_PACI VARCHAR(12),
	NOME_CONVENIO VARCHAR(20),
	CNPJ VARCHAR(20),
	TEMPO_CARENCIA VARCHAR(20),
	FOREIGN KEY(CPF_PACI) REFERENCES PACIENTE(CPF_PACI)
);


CREATE TABLE PACIENTE(
	CPF_PACI VARCHAR(12) PRIMARY KEY,
	NOME_PACI VARCHAR(100),
	RG_PACI VARCHAR(10),
	DATA_NASCI DATE,
	ENDERECO_PACI VARCHAR(30),
	TELEFONE_PACI VARCHAR(20),
	EMAIL_PACI VARCHAR(20),
	COD_CONVENIO INT,
	FOREIGN KEY(COD_CONVENIO) REFERENCES CONVENIO(COD_CONVENIO)

);

CREATE TABLE MEDICO(
	NUM_CRM VARCHAR(20),
	NOME_MED VARCHAR(30),
	ENDERECO_MED VARCHAR(30),
	EMAIL_MED VARCHAR(20),
	DATA_NASCI DATE,
	TELEFONE_MED VARCHAR(15),
	PRIMARY KEY(NUM_CRM)
);


CREATE TABLE Generalista (
    COD_Generalista INT,
    NUM_CRM VARCHAR(20),
	PRIMARY KEY(COD_Generalista,NUM_CRM),
    FOREIGN KEY (NUM_CRM) REFERENCES Medico(NUM_CRM)
);

CREATE TABLE Especialista (
    COD_Especialista INT,
    NUM_CRM VARCHAR(20),
	PRIMARY KEY(COD_ESPECIALISTA),
    FOREIGN KEY (NUM_CRM) REFERENCES Medico(NUM_CRM)
);


CREATE TABLE ESPECIALIDADE(
	COD_ESPECIALIDADE INT,
	COD_ESPECIALISTA INT,
	NOME_ESPECIALIDADE VARCHAR(30),
	PRIMARY KEY(COD_ESPECIALIDADE),
	FOREIGN KEY(COD_ESPECIALISTA) REFERENCES ESPECIALISTA(COD_Especialista)
);


CREATE TABLE Residente (
    COD_Residente INT,
    NUM_CRM VARCHAR(20),
	PRIMARY KEY(COD_RESIDENTE,NUM_CRM),
    FOREIGN KEY (NUM_CRM) REFERENCES Medico(NUM_CRM)
);

CREATE TABLE MEDICO_CONVENIO(
	NUM_CRM VARCHAR(20),
	COD_CONVENIO INT,
	PRIMARY KEY(NUM_CRM,COD_CONVENIO),
	FOREIGN KEY(NUM_CRM) REFERENCES MEDICO(NUM_CRM),
	FOREIGN KEY(COD_CONVENIO) REFERENCES CONVENIO(COD_CONVENIO)
);


CREATE TABLE ENFERMEIRO(
	COD_ENFERMEIRO INT,
	NUM_COREN VARCHAR(20),
	NOME VARCHAR(30),
	CPF VARCHAR(12),
	PRIMARY KEY(COD_ENFERMEIRO)
);

CREATE TABLE ENFERMEIRO_INTERNACAO(
	COD_ENFERMEIRO INT,
	COD_INTERNACAO INT,
	PRIMARY KEY(COD_ENFERMEIRO,COD_INTERNACAO),
	FOREIGN KEY(COD_ENFERMEIRO) REFERENCES ENFERMEIRO(COD_ENFERMEIRO),
	FOREIGN KEY(COD_INTERNACAO) REFERENCES INTERNACAO(COD_INTERNACAO)
);

CREATE TABLE QUARTO(
	COD_QUARTO INT,
	CPF_PACI VARCHAR(12),
	NUM_QUARTO VARCHAR(10),
	COD_INTERNACAO INT,
	TIPO VARCHAR(20)
	PRIMARY KEY(COD_QUARTO),
	FOREIGN KEY(CPF_PACI) REFERENCES PACIENTE(CPF_PACI),
	FOREIGN KEY(COD_INTERNACAO) REFERENCES INTERNACAO(COD_INTERNACAO)
);


CREATE TABLE CONSULTA(
	COD_CONSULTA INT,
	COD_CONVENIO INT,
	DATA_CONSULTA DATE,
	HORARIO TIME,
	NUM_CARTEIRA INT,
	COD_ESPECIALIDADE INT,
	NUM_CRM VARCHAR(20),
	CPF_PACI VARCHAR(12),
	PRIMARY KEY(COD_CONSULTA),
	FOREIGN KEY(COD_ESPECIALIDADE) REFERENCES ESPECIALIDADE(COD_ESPECIALIDADE),
	FOREIGN KEY(NUM_CRM) REFERENCES MEDICO(NUM_CRM),
	FOREIGN KEY(CPF_PACI) REFERENCES PACIENTE(CPF_PACI),
	FOREIGN KEY(COD_CONVENIO) REFERENCES CONVENIO(COD_CONVENIO)
);

CREATE TABLE COBRE(
	COD_CONVENIO INT,
	COD_CONSULTA INT,
	VALOR_CONSULTA DECIMAL(10,2),
	PRIMARY KEY (Cod_Convenio, Cod_Consulta),
    FOREIGN KEY (Cod_Convenio) REFERENCES Convenio(Cod_Convenio),
    FOREIGN KEY (Cod_Consulta) REFERENCES Consulta(Cod_Consulta)
);


CREATE TABLE RECEITA(
	COD_RECEITA INT,
	COD_CONSULTA INT,
	CPF_PACI VARCHAR(12),
	INSTRUCOES VARCHAR(200),
	QUANTIDADE VARCHAR(50),
	MEDICAMENTO VARCHAR(50),
	PRIMARY KEY(COD_RECEITA),
	FOREIGN KEY(COD_CONSULTA) REFERENCES CONSULTA(COD_CONSULTA),
	FOREIGN KEY(CPF_PACI) REFERENCES PACIENTE(CPF_PACI)
);

-- Tabela Principal 
CREATE TABLE Recebimento (
    ID_Recebimento INT PRIMARY KEY,
    Data_Recebimento DATE
);

-- Tabela para Email
CREATE TABLE Recebimento_Email (
    ID_Recebimento INT PRIMARY KEY,
    Email VARCHAR(100),
    FOREIGN KEY (ID_Recebimento) REFERENCES Recebimento(ID_Recebimento)
);

-- Tabela para Impresso
CREATE TABLE Recebimento_Impresso (
    ID_Recebimento INT PRIMARY KEY,
    Endereco VARCHAR(255),
    FOREIGN KEY (ID_Recebimento) REFERENCES Recebimento(ID_Recebimento)
);


CREATE TABLE INTERNACAO(
	COD_INTERNACAO INT,
	CPF_PACI VARCHAR(12),
	NUM_CRM VARCHAR(20),
	DATA_ENTRADA DATE,
	DATA_ALTA DATE,
	DATA_PREV_ALTA DATE,
	PROCEDIMENTO VARCHAR(300),
	PRIMARY KEY(COD_INTERNACAO),
	FOREIGN KEY(CPF_PACI) REFERENCES PACIENTE(CPF_PACI),
	FOREIGN KEY(NUM_CRM) REFERENCES MEDICO(NUM_CRM)
);

CREATE TABLE TIPO_QUARTO(
	COD_TIPO_QUARTO INT,
	COD_QUARTO INT,
	VALOR_DIARIO DECIMAL,
	DESCRICAO VARCHAR(100),
	PRIMARY KEY(COD_TIPO_QUARTO),
	FOREIGN KEY(COD_QUARTO) REFERENCES QUARTO(COD_QUARTO)
);